### ISSUE TITLE
Another error while starting a server in console

### ISSUE THREAD

**Issue by ghost** [thebigsmileXD/fireworks#14]
Latest version PocketMine-MP 1.7dev-656 「[REDACTED]」 implementing API version 3.0.0-ALPHA10 for Minecraft: PE v1.2.7 (protocol version 160)

[Server thread/CRITICAL]: ErrorException: "Declaration of xenialdan\fireworks\item\Fireworks::onActivate(pocketmine\level\Level $level, pocketmine\Player $player, pocketmine\block\Block $blockReplace, pocketmine\block\Block $blockClicked, int $face, pocketmine\math\Vector3 $clickVector): bool should be compatible with pocketmine\item\Item::onActivate(pocketmine\Player $player, pocketmine\block\Block $blockReplace, pocketmine\block\Block $blockClicked, int $face, pocketmine\math\Vector3 $clickVector): bool" (EXCEPTION) in "fireworks-master/src/xenialdan/fireworks/item/Fireworks" at line 77

**Comment by xXNiceYT** [comment]
@Antisa14200 try using lastest version of pmmp, I got same bug I used lastest pmmp it worked.

**Comment by ghost** [comment]
I do

Dana 26. sij 2018. 03:50 osoba "xXNiceYT" <notifications@github.com>
napisala je:

**Comment by ghost** [comment]
Those changes from the latest version of Pocketmine seem to be a cause of this https://github.com/pmmp/PocketMine-MP/commit/6c8a1a5b80e9700cdbeb92adf4146fd9a0d299dc
