### ISSUE TITLE
stupid plug 

### ISSUE THREAD

**Issue by opkiler22789** [thebigsmileXD/Fireworks#2]
stupid plug, triggers the torch to the top and nothing else does

**Comment by thebigsmileXD** [comment]
I wonder why you took a look at the plugin then ;)

**Comment by thebigsmileXD** [comment]
By the way, this is a plug: https://www.aliexpress.com/cheap/cheap-diamond-plug.html

**Comment by MechRalph04** [comment]
An issue is a problem... I guess...
